; Copyright © 2022-2025 SkyLabs AI.
;
; This file is CONFIDENTIAL AND PROPRIETARY to BlueRock. All rights reserved.
;
; Use of this file is only permitted subject to a separate written license agreement with BlueRock.

(env
 (sl_timing
  (binaries (../BRiCk/rocq-tools/bin/rocq_perf.exe as rocq))
  (rocq
   (rocqdep_flags :standard -w +all)
   (flags (:standard %{read-lines:flags/coqc}))))
 ; Same, but without rocq_perf
 (_
  (rocq
   (rocqdep_flags :standard -w +all)
   (flags (:standard %{read-lines:flags/coqc})))))
